require 'bigdecimal'

require_relative 'corpus/word'
require_relative 'corpus/bigram'
#require_relative 'corpus/word_table'
#require_relative 'corpus/bigram_table'
require_relative 'corpus/letter_node'
require_relative 'corpus/scanner'
require_relative 'corpus/analysis'
require_relative 'corpus/analysis/words'
require_relative 'corpus/analysis/bigrams'
require_relative 'corpus/layout'
require_relative 'corpus/cli'
require_relative 'corpus/main'

